### ISSUE TITLE
Lib-ify

### ISSUE THREAD

**Issue by KaiBot3000** [mapbox/price-pigeon#2]
Separate functions into "CLI-specific code" and "library code".

**Comment by KaiBot3000** [comment]
Working on this in branch [`lib2`](https://github.com/mapbox/price-pigeon/tree/lib2). 

I originally used [@mapbox/amis](https://github.com/mapbox/amis) as my example for building a module that makes API requests. I followed a similar flow, where the initial function (`getResponse`) makes an API request (or reads a file), then calls `createMapping` on the response.

I moved the helper functions like `formatMap` into a lib file, but I'm not sure how to unstick `getResponse` and `createMapping` so they can be called separately without making a mess.

**Comment by yhahn** [comment]
@KaiBot3000 I wonder if you want to think of `createMapping()` as a wrapper that glues together all the steps:
- getResponse (makes the HTTP/file retrieval, provides unmodified JSON data back)
- pushes that through parsing/formatting
- writes the file output

This way it's really the only function that proceeds to the "next" step by calling another of your functions. All the rest do their own standalone thing, and rather than having a decision about what should happen next they pass the buck to the callback.

**Comment by KaiBot3000** [comment]
Yeah! I want that. What I haven't figured out is how to wait around for getResponse to finish without using createMapping as a callback, which seems to defeat the purposed of having one wrapper function.

**Comment by KaiBot3000** [comment]
Well, the answer is still using createMapping as a callback, but now everything is tidied away in a lib file in [`nocallbacksies`](https://github.com/mapbox/price-pigeon/tree/nocallbacksies)

**Comment by yhahn** [comment]
:+1:

**Comment by KaiBot3000** [comment]
Fixed w/ https://github.com/mapbox/price-pigeon/pull/3
